<?php
namespace Tests\Feature;
use App\Models\Permission;use App\Models\Role;use App\Models\User;use App\Modules\Auth\Application\UseCases\AuthenticateUser;use App\Modules\Auth\Domain\Contracts\AuthorizationServiceInterface;use App\Modules\Auth\Domain\Exceptions\AuthenticationException;use App\Modules\Auth\Domain\Exceptions\AuthorizationException;use Database\Seeders\RbacSeeder;use Illuminate\Foundation\Testing\RefreshDatabase;use Tests\TestCase;
final class RbacSecurityTest extends TestCase {
 use RefreshDatabase;
 protected function setUp():void{parent::setUp();$this->seed(RbacSeeder::class);}
 public function test_role_matrix_for_manager_product_manager_order_manager_support_and_customer():void{
  $cases=[
   ['manager',['products.create','products.delete','orders.manage'],['settings.update','roles.create','payments.refund']],
   ['product_manager',['products.view','products.create','products.update','products.delete','attributes.create','brands.update','categories.delete'],['orders.manage','settings.update','assistants.create']],
   ['order_manager',['orders.view','orders.manage','orders.verify','orders.confirm','orders.edit','orders.cancel'],['products.create','products.delete','categories.update','settings.update']],
   ['support_agent',['customers.view','customer.orders.view','customer.addresses.view','customer.notifications.view','orders.view'],['products.create','products.delete','orders.manage','payments.refund','settings.update','roles.create']],
   ['customer',['customer.profile.view','customer.profile.update','customer.addresses.view','customer.addresses.manage','customer.orders.view','customer.cart.view','customer.cart.manage','customer.wishlist.view','customer.wishlist.manage','customer.preferences.manage','customer.notifications.view'],['products.create','products.delete','orders.manage','settings.update','roles.create']],
  ];
  foreach($cases as [$role,$allows,$denies]){$user=$this->userWithRole($role);foreach($allows as $permission)$this->assertPermission($user,$permission,true);foreach($denies as $permission)$this->assertPermission($user,$permission,false);}
 }
 public function test_owner_has_every_seeded_permission():void{$owner=$this->userWithRole('owner');foreach(Permission::query()->pluck('slug') as $permission)$this->assertPermission($owner,$permission,true);}
 public function test_multiple_roles_union_permissions_without_inventing_permissions():void{$user=$this->userWithRole('product_manager');$user->roles()->attach(Role::query()->where('slug','order_manager')->firstOrFail());$this->assertPermission($user,'products.create',true);$this->assertPermission($user,'orders.manage',true);$this->assertPermission($user,'settings.update',false);}
 public function test_explicit_user_override_has_priority_over_role_resolution():void{$user=$this->userWithRole('product_manager');$delete=Permission::query()->where('slug','products.delete')->firstOrFail();$user->permissionOverrides()->attach($delete,['allowed'=>true]);$this->assertPermission($user,'products.delete',true);$owner=$this->userWithRole('owner');$owner->permissionOverrides()->attach($delete,['allowed'=>false]);$this->assertPermission($owner,'products.delete',false);}
 public function test_role_and_permission_removal_revoke_access():void{$role=Role::query()->where('slug','product_manager')->firstOrFail();$user=$this->userWithRole('product_manager');$this->assertPermission($user,'products.create',true);$role->permissions()->detach(Permission::query()->where('slug','products.create')->firstOrFail());$this->assertPermission($user,'products.create',false);$role->permissions()->attach(Permission::query()->where('slug','products.create')->firstOrFail());$user->roles()->detach($role);$this->assertPermission($user,'products.create',false);}
 public function test_disabled_role_and_disabled_user_cannot_authorize_or_use_protected_endpoint():void{$role=Role::query()->where('slug','product_manager')->firstOrFail();$user=$this->userWithRole('product_manager');$role->update(['is_active'=>false]);$this->assertPermission($user,'products.create',false);$role->update(['is_active'=>true]);$user->update(['status'=>'inactive']);$this->actingAs($user)->getJson('/api/v1/customer/profile')->assertUnauthorized();$this->expectException(AuthenticationException::class);app(AuthenticateUser::class)->execute();}
 public function test_unknown_permission_is_a_clean_denial_and_authorize_use_case_maps_to_403():void{$user=$this->userWithRole('customer');$this->assertPermission($user,'permission.unknown',false);$this->actingAs($user)->getJson('/api/v1/customer/profile')->assertOk();$this->expectException(AuthorizationException::class);app(\App\Modules\Auth\Application\UseCases\AuthorizeUser::class)->execute($user,'permission.unknown');}
 public function test_seeder_is_idempotent_and_slugs_are_unique():void{$this->seed(RbacSeeder::class);$this->assertSame(Permission::query()->count(),Permission::query()->distinct('slug')->count());$this->assertSame(Role::query()->count(),Role::query()->distinct('slug')->count());self::assertNotNull(Role::query()->where('slug','support_agent')->first());self::assertNotNull(Role::query()->where('slug','manager')->first());}
 private function userWithRole(string $role):User{$user=User::factory()->create();$user->roles()->attach(Role::query()->where('slug',$role)->firstOrFail());return $user;}
 private function assertPermission(User $user,string $permission,bool $allowed):void{self::assertSame($allowed,app(AuthorizationServiceInterface::class)->allows($user,$permission),"Unexpected {$permission} result for {$user->roles()->pluck('slug')->implode(',')}.");}
}
